num1 = int(input("enter the number: "))
num2 = int(input("enter the number2: "))
print(num1 + num2)
print(num1 - num2)
print(num1 * num2)
print(num1 // num2)
print(num1 > num2)
print(num1 >= num2)
print(num1 < num2)
print(num1 <= num2)
print(num1 == num2)
print(num1 != num2)
